#!/bin/bash

# A script to scale, test, and monitor a Kubernetes deployment.

echo "--- Scaling the deployment to 3 replicas ---"
kubectl scale deployment/django-app-deployment --replicas=3

echo ""
echo "--- Verifying that 3 pods are running (waiting 10 seconds for them to start) ---"
sleep 10
kubectl get pods

echo ""
echo "--- Monitoring resource usage of the pods ---"
kubectl top pods

echo ""
echo "--- Preparing for load test by forwarding a port to the service ---"
kubectl port-forward service/django-app-service 8080:8000 &

PORT_FORWARD_PID=$!

sleep 5

echo ""
echo "--- Running a 10-second load test with wrk ---"
wrk -t2 -c10 -d10s http://localhost:8080

echo ""
echo "--- Stopping the port-forward tunnel ---"
kill $PORT_FORWARD_PID

echo ""
echo "--- Scaling finished. Check the stats above. ---"