name: Django Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: yourpassword  
          MYSQL_DATABASE: test_db          
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # We need to specify the path to the requirements file
        pip install -r messaging_app/requirements.txt

    - name: Run Tests
      env:
        DB_NAME: test_db
        DB_USER: root
        DB_PASSWORD: yourpassword
        DB_HOST: 127.0.0.1 
        DB_PORT: 3306
      run: |
        # Change into the app directory before running tests
        cd messaging_app
        pytest
