pipeline {
    agent any

    tools {
        python 'Python-3.10'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-credentials', 
                    url: 'https://github.com/gemgeek/alx-backend-python.git', 
                    branch: 'main' 
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m pytest --junitxml=test-reports/results.xml'
                }
            }
        }

        stage('Publish Test Report') {
            post {
                always {
                    junit 'messaging_app/test-reports/*.xml'
                }
            }
        }
    }
}